Update and rename xx.json to de.json
CubeCoders/AMPTranslations pull request #2
Opened 2022-09-05 19:54 UTC by Taranuka

german translation.

2022-10-12 18:03 UTC, IceOfWraith commented
I think you accidentally named the file en.json instead of de.json. :)

2022-10-12 18:16 UTC, IceOfWraith commented
Lol! Disregard... My browser translated that automatically...

2022-10-12 21:39 UTC, BroOtti requested changes
Suggested some changes

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "SMTP Server Address": "SMTP-Serveradresse",
SMTP Server

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "SMTP Username": "SMTP-Benutzername",
SMTP Benutzername

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Email 'From' address": "E-Mail-Absenderadresse",
SMTP Absenderadresse

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Stored Backups": "Gespeicherte Sicherungen",
Vorhandende Sicherungen

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Taken By": "Genommen von",
Erstellt durch

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "A description of the backup and why you're taking it (optional)": "Eine Beschreibung der Sicherung und warum Sie es nehmen (optional)",
Eine Beschreibung der Sicherung und warum du sie erstellst (optional)

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Create Backup": "Eine Sicherung erstellen",
Sicherung erstellen

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Are you sure you wish to delete this backup?": "Möchten Sie diese Sicherung wirklich löschen?",
Bist du sicher, dass du diese Sicherung löschen möchtest?

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Are you sure you wish to restore this backup? Any files in this archive will overwrite any with the same name that already exist.": "Möchten Sie diese Sicherung wirklich wiederherstellen? Alle D
Bist du sicher, dass du diese Sicherung wiederherstellen möchtest? Jede Datei dieses Archivs wird bereits existierende Dateien überschreiben.

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Download file here": "Datei herunterladen",
Datei hierhin herunterladen

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Are you sure you want to move the selected item to the trash?": "Möchten Sie das ausgewählte Element wirklich in den Papierkorb verschieben?",
Bist du sicher, dass du die ausgewählte Datei löschen möchtest?

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Delete Item": "Eigenschaft löschen",
Datei löschen

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Please enter a new directory name": "Bitte geben Sie einen neuen Verzeichnisnamen ein",
Bitte gebe einen neuen Ordnernamen ein

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Please enter a new filename": "Proszę wprowadzić nową nazwę pliku",
Bitte gebe einen neuen Dateinamen ein

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Please enter a name for the new directory": "Bitte geben Sie einen Namen für den neuen Ordner ein",
Bitte gebe einen Namen für den neuen Ordner ein

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "You have no files in the clipboard to paste": "Sie haben keine Dateien in der Zwischenablage zum Einfügen",
Du hast keine Dateien in der Zwischenablage zum Einfügen

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Want help fast?": "Brauchen Sie schnelle Hilfe?",
Willst du schnell Hilfe erhalten?

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Otherwise, for support with AMP please visit the": "Andernfalls besuchen Sie für Hilfe mit AMP bitte das ",
Andernfalls besuche für Hilfe mit AMP bitte das

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Always make sure to include the information listed below.": "Achten Sie immer darauf, die unten aufgeführten Informationen anzugeben.",
Achte immer darauf folgende Informationen anzugeben.

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Restart this AMP instance": "Diese AMP-Instant neustarten",
Diese AMP Instanz neustarten

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Upgrade this AMP instance": "Diese AMP-Instanz aktualisieren",
Diese AMP Instanz aktualisieren

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Upgrading this instance may take up to 5 minutes. You will not be able to log into any instances that depend on this ADS instance.": "Die Aktualisierung dieser Instanz kann bis zu 5 Minuten daue
Die Aktualisierung dieser Instanz kann bis zu 5 Minuten dauern. Du kannst dich in keine Instanz anmelden, die von dieser ADS Instanz abhängig ist.

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Keep Running": "gestartet",
Instanz gestartet lassen

2022-10-12 21:39 UTC, BroOtti commented on de.json
> +    "Upgrade Now": "Jetzt upgraden"
Jetzt aktualisieren

2022-10-13 14:13 UTC, BroOtti commented
Just to mention it. There are still many translations missing. At least I enabled the translator mode and got a file with over 500 lines. I also haven't checked if the translations fit in their place :)

2022-10-14 08:27 UTC, gOOvER commented on de.json
> +    "Simple Time Interval": "Einfaches Zeitintervall",
Intervall ist aber nicht wirklich ein Zeitplan

2022-10-14 08:39 UTC, gOOvER commented
Mike should be add the translations into a Translationssystem like Weblate

2022-10-14 10:18 UTC, Taranuka reviewed
top

2022-10-15 09:59 UTC, Taranuka commented
> > top
> 
> Did you just mark all my suggested changes without any changes or discussion? Just to note, some of my suggestions need to be discussed and maybe just personal flavor. Some suggestions are for a better wording and others are for a unified wording. So just marking everything as resolved without any changes won't lead to an approval from me. PS: You also mistyped one word in the translation :) So at least that needs to be fixed before somebody should approve the request :D

Sorry. It is my first try on GitHub. Actually I dont know to use most features. Probably you could help?

 Your suggestions are fine. How I take over your suggestions without to edit 60+ lines?

For most translations I used Google translate. Some I have changed for a more approbiate meaning.

2022-10-15 10:14 UTC, BroOtti commented
> Sorry. It is my first try on GitHub. Actually I dont know to use most features. Probably you could help?
> 
> Your suggestions are fine. How I take over your suggestions without to edit 60+ lines?
> 
> For most translations I used Google translate. Some I have changed for a more approbiate meaning.

No prob :D It's also my first try on GitHub ^^ So I don't know if there's a better way to do it. I think you need to edit the file yourself and create a new commit. Just go comment for comment :) Best would be to reply to my comments and then after you changed it or we discussed it marking it as resolved.
Also, feel free to ask me why I suggested some of the changes :) I'm not perfect :D There could be still better translations :)

2022-10-18 08:10 UTC, BroOtti commented on de.json
> +    "Simple Time Interval": "Einfaches Zeitintervall",
Ja, stimmt schon :D Dann belassen wir das bei Intervall :)

2022-10-18 08:30 UTC, BroOtti commented
I installed a Weblate instance to make it easier for us :)
https://weblate.bromunity.de/projects/amp-translations/github/
I generated my own en.json file and imported your PR to the german translation. Not all strings are included in my generated en.json. Feel free to update my en.json template inside https://github.com/BroOtti/AMPTranslations

2023-08-03 14:58 UTC, PhonicUK approved these changes

2023-08-03 15:02 UTC, PhonicUK reviewed
What do you make of this feedback from ChatGPT?

Overall, the translations look solid, but there are some inconsistencies, typographical issues, and places where the translation could be improved. Here's a detailed list:

Months and Days Abbreviation:
---

* The abbreviations for months and days of the week are not commonly used in German. You can keep the full name of the months, and for the short days of the week, you can consider using the first two letters (e.g., "Mo", "Di", etc.).

Typographical Mistakes:
---

* "beim booten starten" should be "beim Booten starten" with a capital "B".
* "Instanz und die Anwenndung starten" has a typo, it should be "Instanz und die Anwendung starten".
* "Instanz beim booten starten" should be "Instanz beim Booten starten".

Inconsistencies:
---

* You've used "Aktualisieren" for the "Update" and "Refresh" keys. While not incorrect, you might want to differentiate them, e.g., "Update" could be "Aktualisieren" and "Refresh" could be "Erneuern" or "Neu laden."

Grammatical and Stylistic Improvements:

* "nichts machen" could be more naturally translated as "Nichts tun."
* "Kann nicht gestartet werden" might be better as "Kann nicht ausgeführt werden."
* "Bestätigen Sie das Herunterfahren" might be better as "Herunterfahren bestätigen."

Potentially Confusing Translations:
---

* "Sicherung" for "Backups" is technically correct, but "Backups" is also commonly used in German IT context and might be more recognizable to users.
* "Speichernutzung" for "Memory Usage" is correct, but "Arbeitsspeichernutzung" might be more precise.
* "CPU auslastung" should be "CPU-Auslastung" (with a hyphen).
* "Bestätigen Sie das Herunterfahren" is a bit formal. Consider using "Herunterfahren bestätigen."

Other Considerations:
---

* There are some technical terms that could be left in English depending on the target audience, such as "Endpoint", "Instance", "Docker Container", etc. Consider the context and the users' familiarity with these terms in German.
* There's an inconsistency with "Instanz beenden" and "Instanz starten" versus "Instanz löschen" and "Instanz erstellen". Consider using "Instanz stoppen" instead of "Instanz beenden" to maintain uniformity.
* There might be more specific translations for some terms based on the context of your application. If this is a specialized software, the users might expect certain terminology.
* Please update the translations based on these suggestions to ensure accuracy and consistency.

2023-08-04 10:05 UTC, BroOtti commented
Most of the feedback from ChatGPT was already in my change suggestions :D But this Pull Request here is a bit out of date. Pull Request #6 is a more complete version and also used this PR as base. PR #6 was made with the help of my weblate instance and includes contributions from multiple people at Discord.

2023-11-15 14:37 UTC, PhonicUK approved these changes

2023-11-15 14:37 UTC, merged

2023-11-15 14:52 UTC, IceOfWraith commented
Just a heads up, this is an incomplete translation due to the recent changes added to AMP to allow pulling more. I'll find the code snippet Mike provided to grab more. But even then, there isn't an easy way to maintain this as more strings are added to the AMP GUI.